create table student(
	id varchar2(10) not null primary key,
	name varchar2(20) not null,
	age int not null,
	sex char(6) not null
);
create table subject(
	id varchar2(10) not null primary key,
	subject nvarchar2(20) not null,
	teacher nvarchar2(20) not null,
	description nvarchar2(30) not null
);
create table score(
	id number GENERATED BY DEFAULT AS IDENTITY,
	student_id varchar2(10) not null,
	subject_id varchar2(10) not null,
	score varchar2(4) not null,
	primary key(id),
	foreign key(student_id) references student(id),
	foreign key(subject_id) references subject(id)
);

INSERT INTO student VALUES('001', 'zhangsan', 18, 'male');
INSERT INTO student VALUES('002', 'lisi', 20, 'female');

INSERT INTO subject VALUES('1001', 'Chinese', 'Mr.Wang', 'the exam is easy');
INSERT INTO subject VALUES('1002', 'math', 'Miss Liu', 'the exam is diffcult');

INSERT INTO score(student_id, subject_id, score) VALUES('001', '1001', 80);
INSERT INTO score(student_id, subject_id, score) VALUES('002', '1002', 60);
INSERT INTO score(student_id, subject_id, score) VALUES('001', '1001', 70);
INSERT INTO score(student_id, subject_id, score) VALUES('002', '1002', 60.5);

